# Nixpacks конфигурация для Railway оптимизации
[phases.setup]
nixPkgs = ["nodejs_18", "python3", "gcc"]

[phases.install]
cmd = "npm ci --only=production --no-optional --timeout=120000 && cd backend && npm ci --only=production --no-optional"

[phases.build]
cmd = "cd backend && npm run build"

[start]
cmd = "cd backend && npm start"

[variables]
NODE_ENV = "production"
NPM_CONFIG_PRODUCTION = "false" 